classification:
    explore: true
    file: 'Datasets/star_classification.csv'
    head: true
    dshape: true
    generate_file: true
    df_columns: true
    is_null: true
    duplicated_sum: true
    value_counts: true
    value_counts_column: 'class'
    describe: true
    info: true

clustering:
    explore: true
    file: 'Datasets/Pokemon.csv'
    head: true
    dshape: true
    generate_file: true
    df_columns: true
    is_null: true
    duplicated_sum: true
    value_counts: false
    value_counts_column: ''
    describe: true
    info: true
